# Generated by Django 4.0.6 on 2023-06-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="is_crawler",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
